"""update_auth_device_token_relationships

Revision ID: 01ebaced4813
Revises: c58a8eba4bf2
Create Date: 2025-03-22 02:06:15.435719

"""

# revision identifiers, used by Alembic.
revision = "01ebaced4813"
down_revision = "c58a8eba4bf2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
