"""update_auth_relationships

Revision ID: c58a8eba4bf2
Revises: 8c4c6ddd2a9b
Create Date: 2025-03-22 02:01:29.738995

"""

# revision identifiers, used by Alembic.
revision = "c58a8eba4bf2"
down_revision = "8c4c6ddd2a9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
